/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docreservationsystem;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class pastcons extends javax.swing.JFrame {

    /**
     * Creates new form pastcons
     */
    public pastcons( String patientName) {
        initComponents();
         showAppointments(patientName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jname = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Past Consulations Record");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, 840, 370));

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 160, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 880, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String name=  jname.getText();
        new phome(name).setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    public void showAppointments(String patientName) {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Sr No.");
         tableModel.addColumn("Doctor Name");
        tableModel.addColumn("Consultation Date");
        tableModel.addColumn("Consultation Time");
        tableModel.addColumn("Status");
        tableModel.addColumn("Advice");
        tableModel.addColumn("Tablet Title");
        tableModel.addColumn("Quantity");
        tableModel.addColumn("Timing");
        tableModel.addColumn("Usage Instructions");
    
        try (Connection con = databaseconnection.getConnection()) {
             String query = """
                            SELECT 
                                a.appointment_id, 
                                d.name AS doctor_name, 
                                a.consultation_date, 
                                a.consultation_time, 
                                a.status, 
                                pc.advice, 
                                m.tablet_title, 
                                m.quantity, 
                                m.timing, 
                                m.usage_instructions
                            FROM 
                                appointment a
                            JOIN 
                                patient p ON a.patient_id = p.patient_id
                            JOIN 
                                doctor d ON a.doctor_id = d.doctor_id
                            LEFT JOIN 
                                past_consultation pc ON pc.appointment_id = a.appointment_id AND pc.patient_id = a.patient_id
                            LEFT JOIN 
                                medication m ON m.patient_id = p.patient_id
                            WHERE 
                                p.name = ?
                            ORDER BY 
                                a.consultation_date DESC;""";
           PreparedStatement stmt = con.prepareStatement(query);
           stmt.setString(1,patientName );
             ResultSet rs = stmt.executeQuery(); 

            // Clear the table
            tableModel.setRowCount(0);  // Clear previous data
int appointmentNo = 1;
            // Iterate through the result set and populate the table
            while (rs.next()) {
                 String doctorName = rs.getString("doctor_name");
                    Date consultationDate = rs.getDate("consultation_date");
                    Time consultationTime = rs.getTime("consultation_time");
                    String status = rs.getString("status");
                    String advice=rs.getString("advice");
                    String title=rs.getString("tablet_title");
                    int q=rs.getInt("quantity");
                    String r=rs.getString("timing");
                    String i= rs.getString("usage_instructions");
                    
                tableModel.addRow(new Object[]{
                    appointmentNo++,doctorName,consultationDate,consultationTime,status,advice,title,q,r,i
                });
                table.setModel(tableModel);
        }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    public static void main(String args[]) {
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jname;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
